//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListaOperacoes.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacoes
    {
        public int CodigoOperacao { get; set; }
        public string NomeOperacao { get; set; }
        public string NomeMercadoria { get; set; }
        public decimal Quantidade { get; set; }
        public decimal Preco { get; set; }
        public int TipoNegocio { get; set; }
        public string TipoMercadoria { get; set; }
    }
}
